version: '3.7'
name: area
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.docker

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env.docker
    restart: always

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    hostname: api
    volumes:
      - ./api/:/app
    environment:
      - MICROSERVICE=api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  auth:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: auth
    hostname: auth
    volumes:
      - ./api/:/app
    environment:
      - MICROSERVICE=auth
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  service:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: service
    hostname: service
    volumes:
      - ./api/:/app
    environment:
      - MICROSERVICE=service
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  applet:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: applet
    hostname: applet
    volumes:
      - ./api/:/app
    environment:
      - MICROSERVICE=applet
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  discord:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: discord
    hostname: discord
    volumes:
      - ./api/:/app
    environment:
      - MICROSERVICE=discord
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  spotify:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: spotify
    hostname: spotify
    volumes:
      - ./api/:/app
    environment:
      - MICROSERVICE=spotify
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  timer:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: timer
    hostname: timer
    volumes:
      - ./api/:/app
    environment:
      - MICROSERVICE=timer
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  queue:
    image: node:18
    container_name: queue
    hostname: queue
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api/:/home/node/app
    env_file:
      - .env.docker
    command: "npx ts-node --project tsconfig.json ./script/cron.ts"
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  front:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: front
    hostname: front
    env_file:
      - .env.docker
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"
    depends_on:
      - mysql
      - rabbitmq
      - api
