const GOOGLE_ANDROID_CLIENT_ID = '';
const GOOGLE_IOS_CLIENT_ID = '';

const GITHUB_CLIENT_ID = '';
const GITHUB_CLIENT_SECRET = '';

const SPOTIFY_CLIENT_ID = '';
const SPOTIFY_CLIENT_SECRET = '';

const FACEBOOK_APP_ID = '';

const REDIRECT_URI = '';

export const env = {
  GOOGLE_ANDROID_CLIENT_ID,
  GOOGLE_IOS_CLIENT_ID,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  SPOTIFY_CLIENT_ID,
  SPOTIFY_CLIENT_SECRET,
  FACEBOOK_APP_ID,
  REDIRECT_URI,
};
