import { Injectable } from '@nestjs/common';
import {
  ActionAppletEntity,
  ActionRelations,
  ActionService,
} from '@app/common';

const i = 0;
const data = {
  status: 'OK',
  copyright:
    'Copyright (c) 2023 The New York Times Company.  All Rights Reserved.',
  num_results: 20,
  results: [
    {
      slug_name: '31EXPERT-DENTIST-HALLOWEEN-ESP',
      section: 'En español',
      subsection: '',
      title:
        '¿Cómo protege una dentista los dientes de su familia en Halloween?',
      abstract:
        'Una profesional comparte cinco consejos para controlar el consumo de golosinas en este dulce día festivo.',
      uri: 'nyt://article/4e9ba8ad-32dc-5466-980d-7318e39815a0',
      url: 'https://www.nytimes.com/es/2023/10/31/espanol/halloween-dulces-dientes.html',
      byline: 'By Alice Callahan',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T13:12:41-04:00',
      created_date: '2023-10-31T13:12:41-04:00',
      published_date: '2023-10-31T13:12:41-04:00',
      first_published_date: '2023-10-31T13:12:41-04:00',
      material_type_facet: 'News',
      kicker: '¿Cómo un experto…?',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31venezuela-opposition',
      section: 'World',
      subsection: '',
      title:
        'Venezuela Tries to Squash Opposition Campaign Before It Even Starts',
      abstract:
        'The government’s move to annul the election of a candidate to challenge President Nicolás Maduro raises questions about its commitment to a free election.',
      uri: 'nyt://article/cd318c23-4f42-5cb6-ac65-0669282cd358',
      url: 'https://www.nytimes.com/2023/10/31/world/maduro-venezuela-election.html',
      byline: 'By Genevieve Glatsky',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T13:11:15-04:00',
      created_date: '2023-10-31T13:11:15-04:00',
      published_date: '2023-10-31T13:11:15-04:00',
      first_published_date: '2023-10-31T13:11:15-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [Array],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31hochul-hate-crimes',
      section: 'New York',
      subsection: '',
      title:
        'Gov. Hochul Announces $75 Million to Combat Hate Crimes in New York',
      abstract:
        'The governor announced grants for houses of worship and local police departments following an uptick in antisemitic attacks.',
      uri: 'nyt://article/9a439bb3-2936-5f52-b27b-cd273c86482a',
      url: 'https://www.nytimes.com/2023/10/31/nyregion/hochul-hate-crimes-ny.html',
      byline: 'By Luis Ferré-Sadurní',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T13:00:00-04:00',
      created_date: '2023-10-31T13:00:01-04:00',
      published_date: '2023-10-31T13:00:01-04:00',
      first_published_date: '2023-10-31T13:00:01-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [Array],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31Off',
      section: 'Food',
      subsection: '',
      title:
        'After Decades in the Restaurant Business, Andrew Carmellini Opens Café Carmellini',
      abstract:
        'Marcus Samuelsson opens Metropolis in the new Perelman Performing Arts Center, Blue Ribbon adds a chop house spot to its lineup and more restaurant news.',
      uri: 'nyt://article/5b118e86-1eb5-59a9-a2d1-92e7164e01c6',
      url: 'https://www.nytimes.com/2023/10/31/dining/andrew-carmellini-cafe-carmellini.html',
      byline: 'By Florence Fabricant',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:58:17-04:00',
      created_date: '2023-10-31T12:58:17-04:00',
      published_date: '2023-10-31T12:58:17-04:00',
      first_published_date: '2023-10-31T12:58:17-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31x-reading',
      section: 'Arts',
      subsection: 'Music',
      title: 'The Met Opera Puts On a Malcolm X Marathon',
      abstract:
        'Ahead of its new production of Anthony Davis’s “X,” the house hosted a starry, 18-hour reading of Malcolm X’s autobiography.',
      uri: 'nyt://article/a267fa86-22a8-5f44-a576-8d0bec6d3679',
      url: 'https://www.nytimes.com/2023/10/31/arts/music/malcolm-x-met-opera.html',
      byline: 'By Reggie Ugwu and Elliott Jerome Brown Jr.',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:56:30-04:00',
      created_date: '2023-10-31T12:56:30-04:00',
      published_date: '2023-10-31T12:56:30-04:00',
      first_published_date: '2023-10-31T12:56:30-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [Array],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31israel-hostages',
      section: 'World',
      subsection: 'Middle East',
      title: 'Israel Faces Hostage Dilemma in Gaza',
      abstract:
        'The country has said there are two main goals in the war: Destroy Hamas and free the hostages held in Gaza. But are those goals compatible?',
      uri: 'nyt://article/6d8c348f-d65e-5b42-ada1-94c13ff82b51',
      url: 'https://www.nytimes.com/2023/10/31/world/middleeast/israel-hostages-gaza-hamas.html',
      byline: 'By Adam Goldman and Eric Schmitt',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T13:15:23-04:00',
      created_date: '2023-10-31T12:44:43-04:00',
      published_date: '2023-10-31T12:44:43-04:00',
      first_published_date: '2023-10-31T12:44:43-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31israel-hamas-fighting',
      section: 'World',
      subsection: 'Middle East',
      title:
        'Israeli forces reach a neighborhood north of Gaza City, the enclave’s interior ministry said.',
      abstract: '',
      uri: 'nyt://article/37b56d3c-a6ea-5618-aa26-7f325a4b7e50',
      url: 'https://www.nytimes.com/live/2023/10/31/world/israel-hamas-war-gaza-news/israeli-forces-reach-a-neighborhood-north-of-gaza-city-the-enclaves-interior-ministry-said',
      byline: 'By Matthew Mpoke Bigg and Hiba Yazbek',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:40:14-04:00',
      created_date: '2023-10-31T12:35:04-04:00',
      published_date: '2023-10-31T12:35:04-04:00',
      first_published_date: '2023-10-31T12:35:04-04:00',
      material_type_facet: 'Live Blog Post',
      kicker: '',
      subheadline: '',
      des_facet: [],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31cli-newsletter-web',
      section: 'Climate',
      subsection: '',
      title: 'It’s All About the Grid',
      abstract: 'Billions of dollars in new U.S. funding won’t be enough',
      uri: 'nyt://article/91f3d2d7-870b-5db6-9710-959def48a363',
      url: 'https://www.nytimes.com/2023/10/31/climate/its-all-about-the-grid.html',
      byline: 'By David Gelles',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:30:10-04:00',
      created_date: '2023-10-31T12:30:10-04:00',
      published_date: '2023-10-31T12:30:10-04:00',
      first_published_date: '2023-10-31T12:30:10-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [Array],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31artificial-flavors',
      section: 'Theater',
      subsection: '',
      title: '‘Artificial Flavors’ Review: Blame ChatGPT for This Musical',
      abstract:
        'Each performance culminates in a production, composed on the spot, with misguided help from artificial intelligence.',
      uri: 'nyt://article/fa6ac189-f73f-5c44-b23d-11846a6e185d',
      url: 'https://www.nytimes.com/2023/10/31/theater/artificial-flavors-review.html',
      byline: 'By Naveen Kumar',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:24:27-04:00',
      created_date: '2023-10-31T12:24:27-04:00',
      published_date: '2023-10-31T12:24:27-04:00',
      first_published_date: '2023-10-31T12:24:27-04:00',
      material_type_facet: 'Review',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [Array],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31courtney-bryan',
      section: 'Arts',
      subsection: 'Music',
      title: 'Courtney Bryan’s Music Brings It All Together',
      abstract:
        'A recent recipient of the MacArthur “genius” grant, this pianist and composer fuses different styles for a sound that is entirely her own.',
      uri: 'nyt://article/1fa1fc73-3ac0-5cb0-92f9-99806ca0df81',
      url: 'https://www.nytimes.com/2023/10/31/arts/music/courtney-bryan-music.html',
      byline: 'By Seth Colter Walls',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T13:15:51-04:00',
      created_date: '2023-10-31T12:17:06-04:00',
      published_date: '2023-10-31T12:17:06-04:00',
      first_published_date: '2023-10-31T12:17:06-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [Array],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31uaw-labor',
      section: 'Business',
      subsection: 'Economy',
      title: 'U.A.W. Strike Gains Could Reverberate Far Beyond Autos',
      abstract:
        'Experts said the union’s new contracts could set precedents that give labor advantages when bargaining contracts and organizing workers.',
      uri: 'nyt://article/a8cbc6b8-d073-5c33-b082-e518c737952c',
      url: 'https://www.nytimes.com/2023/10/31/business/economy/uaw-labor.html',
      byline: 'By Noam Scheiber',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:16:50-04:00',
      created_date: '2023-10-31T12:16:50-04:00',
      published_date: '2023-10-31T12:16:50-04:00',
      first_published_date: '2023-10-31T12:16:50-04:00',
      material_type_facet: 'News',
      kicker: 'News ANALYSIS',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [Array],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31israel-hamas-holocaust',
      section: 'World',
      subsection: 'Middle East',
      title:
        'Israel’s U.N. Ambassador Criticized for Wearing a Yellow Star of David',
      abstract:
        'Dani Dayan, chairman of Yad Vashem museum in Jerusalem, said Israelis should instead display the country’s flag as a sign of strength.',
      uri: 'nyt://article/e9fca011-da1a-5ca5-90fa-0786d5d9250b',
      url: 'https://www.nytimes.com/2023/10/31/world/middleeast/israel-erdan-yellow-star-of-david.html',
      byline: 'By Matthew Mpoke Bigg',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:02:29-04:00',
      created_date: '2023-10-31T12:02:29-04:00',
      published_date: '2023-10-31T12:02:29-04:00',
      first_published_date: '2023-10-31T12:02:29-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [Array],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31NAT-MAINE-GUNS',
      section: 'U.S.',
      subsection: '',
      title:
        'After Mass Shooting in Maine, No Clarity on Whether Gun Laws Will Change',
      abstract:
        'A state ban on assault weapons? Expanded concealed-carry restrictions? Tighter mental health laws? As Maine grieves, it weighs a roiling debate over gun laws.',
      uri: 'nyt://article/c03a3c43-6306-50da-a0c7-8455528e502f',
      url: 'https://www.nytimes.com/2023/10/31/us/maine-gun-laws-mass-shooting.html',
      byline: 'By Amelia Nierenberg and Jenna Russell',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T12:55:07-04:00',
      created_date: '2023-10-31T12:02:18-04:00',
      published_date: '2023-10-31T12:02:18-04:00',
      first_published_date: '2023-10-31T12:02:18-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [Array],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31israel-military-assess-esp',
      section: 'En español',
      subsection: '',
      title: 'La invasión de Israel a Gaza comenzó con ambigüedad y secretismo',
      abstract:
        'Tras una campaña aérea en la que murieron miles de palestinos, Israel inició un ataque terrestre, pero los observadores externos tardaron horas en comprender lo que ocurría. La ambigüedad era deliberada.',
      uri: 'nyt://article/375819c9-cc03-52f3-b07d-81c74a974d06',
      url: 'https://www.nytimes.com/es/2023/10/31/espanol/guerra-israel-hamas-invasion-gaza.html',
      byline: 'By Patrick Kingsley and Ronen Bergman',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T11:59:04-04:00',
      created_date: '2023-10-31T11:59:04-04:00',
      published_date: '2023-10-31T11:59:04-04:00',
      first_published_date: '2023-10-31T11:59:04-04:00',
      material_type_facet: 'News',
      kicker: 'Análisis de noticias',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31ukraine-killing',
      section: 'World',
      subsection: 'Europe',
      title: 'Russia Detains Two Soldiers Suspected of Killing 9 Civilians',
      abstract:
        'The arrest in an occupied area of Ukraine was a rare admission by Moscow that its forces may have committed a crime against Ukrainian civilians. Experts warned that it might just be political posturing.',
      uri: 'nyt://article/885182d3-0ce2-5a6e-a41c-a7bf1c4bfeef',
      url: 'https://www.nytimes.com/2023/10/31/world/europe/russia-ukraine-killing-atrocities-civilians.html',
      byline: 'By Constant Méheut',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T11:53:44-04:00',
      created_date: '2023-10-31T11:53:44-04:00',
      published_date: '2023-10-31T11:53:44-04:00',
      first_published_date: '2023-10-31T11:53:44-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31weeknight-web',
      section: 'Food',
      subsection: '',
      title: 'Let’s Make Some Meatballs',
      abstract:
        'With plenty of tomato sauce, slabs of garlic bread and a big green salad — that’s dinner.',
      uri: 'nyt://article/c22b5f6d-9ef5-5204-9e16-cf1706d2d233',
      url: 'https://www.nytimes.com/2023/10/31/dining/lets-make-some-meatballs.html',
      byline: 'By Emily Weinstein',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T11:00:02-04:00',
      created_date: '2023-10-31T11:00:02-04:00',
      published_date: '2023-10-31T11:00:02-04:00',
      first_published_date: '2023-10-31T11:00:02-04:00',
      material_type_facet: 'Letter',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31documentary-streaming',
      section: 'Movies',
      subsection: '',
      title: 'Three Great Documentaries to Stream',
      abstract:
        'In this month’s picks, an actor and a director reflect on their careers, while another director reflects on everything else.',
      uri: 'nyt://article/36e51963-dc83-54da-a4a2-b60d822b4e74',
      url: 'https://www.nytimes.com/2023/10/31/movies/documentaries-streaming.html',
      byline: 'By Ben Kenigsberg',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T10:45:26-04:00',
      created_date: '2023-10-31T10:45:26-04:00',
      published_date: '2023-10-31T10:45:26-04:00',
      first_published_date: '2023-10-31T10:45:26-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [Array],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31xp-fairybridge',
      section: 'World',
      subsection: 'Europe',
      title:
        'A Footpath in England, Torn Down, Keeps Being Rebuilt by ‘Fairies’',
      abstract:
        'A small bridge in the English village of Stiffkey, northeast of Cambridge, was dismantled last year. It was rebuilt overnight, dismantled a second time and rebuilt again.',
      uri: 'nyt://article/1099fcb0-e896-54fb-b77e-7c468f20d085',
      url: 'https://www.nytimes.com/2023/10/31/world/europe/norfolk-fairy-bridge-uk-national-trust.html',
      byline: 'By Jenny Gross',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T11:00:37-04:00',
      created_date: '2023-10-31T10:40:53-04:00',
      published_date: '2023-10-31T10:40:53-04:00',
      first_published_date: '2023-10-31T10:40:53-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [Array],
      per_facet: [],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31StudentNewsQuiz',
      section: 'The Learning Network',
      subsection: '',
      title:
        'Weekly Student News Quiz: Gaza Strip, Matthew Perry, World Series',
      abstract:
        'Have you been paying attention to the news recently? See how many of these 10 questions you can get right.',
      uri: 'nyt://interactive/eb9454be-7706-5902-bcab-2290fe7f0241',
      url: 'https://www.nytimes.com/interactive/2023/10/31/learning/31StudentNewsQuiz.html',
      byline: 'Compiled by Katherine Schulten',
      item_type: 'Interactive',
      source: 'New York Times',
      updated_date: '2023-10-31T10:39:16-04:00',
      created_date: '2023-10-31T10:18:17-04:00',
      published_date: '2023-10-31T10:18:17-04:00',
      first_published_date: '2023-10-31T10:18:17-04:00',
      material_type_facet: 'Interactive Feature',
      kicker: 'Student News Quiz',
      subheadline: '',
      des_facet: [],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      related_urls: [],
      multimedia: [Array],
    },
    {
      slug_name: '31xp-perry-cause-ESP',
      section: 'En español',
      subsection: '',
      title: 'Se investiga la causa de la muerte de Matthew Perry',
      abstract:
        'La policía informó que el actor fue hallado inconsciente en un jacuzzi de su casa de Los Ángeles el sábado. Los expertos afirman que establecer la causa de su muerte podría demorar semanas o meses.',
      uri: 'nyt://article/03677d24-afc2-5d39-b5a5-a8b3488fc7f4',
      url: 'https://www.nytimes.com/es/2023/10/31/espanol/matthew-perry-causa-muerte.html',
      byline: 'By Derrick Bryson Taylor and Michael Levenson',
      item_type: 'Article',
      source: 'New York Times',
      updated_date: '2023-10-31T10:09:44-04:00',
      created_date: '2023-10-31T10:09:44-04:00',
      published_date: '2023-10-31T10:09:44-04:00',
      first_published_date: '2023-10-31T10:09:44-04:00',
      material_type_facet: 'News',
      kicker: '',
      subheadline: '',
      des_facet: [Array],
      org_facet: [],
      per_facet: [Array],
      geo_facet: [Array],
      related_urls: [],
      multimedia: [Array],
    },
  ],
};

const NYT_URL =
  'https://api.nytimes.com/svc/news/v3/content/all/all.json?api-key=4fV2CtujvTrqTg6FibLdJDLcmzJt8dT0';

const lastArticleUpdatedDate: string | null = null;

@Injectable()
export class NewsService {
  constructor(private readonly actionService: ActionService) {}

  getConfigs(actionApplet: ActionAppletEntity, keys: string[]): any {
    const configs = {};
    for (const key of keys) {
      const config = actionApplet.configs.find((e) => e.key === key);
      if (!config) continue;
      configs[key] = config;
    }
    return configs;
  }

  async cron(): Promise<void> {
    this.onNewNYTArticle();
  }

  async onNewNYTArticle(): Promise<void> {
    const action = await this.actionService.findOne(
      {
        key: 'nyt_article',
      },
      [
        ActionRelations.APPLET,
        ActionRelations.APPLETS,
        ActionRelations.CONFIGS,
        ActionRelations.USER,
        ActionRelations.ACTION_SERVICE,
        ActionRelations.REACTION_SERVICE,
        ActionRelations.REACTIONS_CONFIG,
        ActionRelations.ACTION_CONFIG,
      ],
    );
    if (!action || !action.is_available) return;
    for (const actionApplet of action.applets) {
      if (!actionApplet.applet.is_active) continue;
    }
    console.log(action);

    /*
    const response = await fetch(NYT_URL, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
    });
    const data = await response.json();
    i++;

    console.log(
      'New NYT article',
      data.results.map((r) => r.updated_date),
    );
     */
  }
}
