version: '3.7'
name: area
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.docker

  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env.docker
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    hostname: api
    volumes:
      - ./:/app
    environment:
      - MICROSERVICE=api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth
    hostname: auth
    volumes:
      - ./:/app
    environment:
      - MICROSERVICE=auth
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cron
    hostname: cron
    volumes:
      - ./:/app
    environment:
        - MICROSERVICE=cron
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always

  discord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord
    hostname: discord
    volumes:
      - ./:/app
    environment:
      - MICROSERVICE=discord
    env_file:
      - .env.docker
    depends_on:
      - mysql
      - rabbitmq
    restart: always
