on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}
          script: |
            cd /home/nathan/area
            git pull
            docker compose up -d --build
            docker image prune -a
