on:
  push:
    branches:
      - main

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-DEV-500-LIL-5-1-area-nathan.delenclos.git"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VM_HOST }}
          username: ${{ vars.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEPLOY }}
          script: |
            cd /home/nathan/area
            git pull
            cd api && yarn && cd ../web && yarn && cd ../mobile && yarn
            sudo docker compose up --build -d && sudo docker image prune -a -f

  push_epitech:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
