on:
  push:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  web_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Move to web folder
        run: cd web
      - name: ls
        run: ls
      - name: Install dependencies
        run: yarn
      - name: Run eslint
        run: yarn run lint

  api_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Move to api folder
        run: cd api
      - name: ls
        run: ls
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run lint

  mobile_linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Move to mobile folder
        run: cd mobile
      - name: ls
        run: ls
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn run lint
